services:
  postgres:
    image: postgres:alpine
    restart: always
    user: postgres
    env_file:
      - path: .env
        required: true
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: dev
    volumes:
      - /mnt/disks/pg_data/data:/var/lib/postgresql/data:z
      # - pg_data:/var/lib/postgresql/data
      - ./config/postgresql.conf:/var/lib/postgresql/data/postgresql.conf:ro
      - ./certs:/var/letsencrypt:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 15s
      retries: 20
    networks:
      - postgres
    deploy:
      resources:
        limits:
          cpus: 1.8
          memory: 900M

networks:
  postgres:
