
entryPoints:
  # http:
  #   address: ":80"
  #   http:
  #     redirections:
  #       entryPoint:
  #         to: "https"
  #         scheme: "https"
  https:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    network: traefik
    exposedByDefault: false

api:
  dashboard: true

log:
  level: INFO #DEBUG 

certificatesResolvers:
  acme_tls:
    acme:
      email: "{{ LETS_ENCRYPT_EMAIL }}" 
      storage: /etc/traefik/certs/acme_tls.json 
#      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory" 
      tlsChallenge: {}
