- name: Assert docker, docker-compose is setup
  ansible.builtin.import_playbook: setup-docker.yml

- name: Deploy using docker images
  vars:
    dest: "/opt/AplikacjaKonie"
    dockercompose: https://raw.githubusercontent.com/NiebieskiRekin/AplikacjaKonie/refs/heads/main/docker-compose.yml
  hosts: main
  tasks:
    - name: Create traefik docker network 
      community.docker.docker_network:
        name: traefik

    - name: Create project directory
      ansible.builtin.file:
        path: "{{ dest }}"
        state: directory
        mode: "0777"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      become: true

    - name: Copy docker-compose.yml
      ansible.builtin.get_url:
        url: "{{ dockercompose }}"
        dest: "{{ dest }}/docker-compose.yml"
        mode: "0660"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        force: true
      become: true

    # TODO: Setup versioned secrets object storage in the future
    - name: Setup .env
      ansible.builtin.copy:
        dest: "{{ dest }}/.env"
        content: |
          {{ lookup('env','ENV_FILE') }}
        mode: "0600"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      become: true

    - name: Start services
      community.docker.docker_compose_v2:
        project_src: "{{ dest }}"
