name: Deploy traefik postgres

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        type: environment
        required: true
        default: development

jobs:
  deploy-traefik-postgres:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    environment: development
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          sparse-checkout: |
            .github
            infra
            docker-compose.lb-db.yml
          sparse-checkout-cone-mode: false

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@a4133a9690f77b38c8227021ed497fc1267635d5 # v3
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          ANSIBLE_HOST: ${{secrets.ANSIBLE_HOST}}
          ANSIBLE_USER: ${{secrets.ANSIBLE_USER}}
          ENV_FILE: "${{ secrets.TRAEFIK_POSTGRES_ENV_FILE }}"
        with:
          # Required, playbook filepath
          playbook: infra/Ansible/playbooks/deploy-lb-db.yml
          # Optional, SSH private key
          key: ${{secrets.SSH_PRIVATE_KEY}}
          # Optional, SSH known hosts file content
          known_hosts: ${{secrets.SSH_KNOWN_HOSTS}}
          options: |
            --inventory infra/Ansible/inventory/inventory.yml
            --verbose
