name: Deploy traefik postgres

on:
  workflow_dispatch:

jobs:
  deploy-traefik-postgres:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: production
          sparse-checkout: |
            .github
            infra
            docker-compose.lb-db.yml
          sparse-checkout-cone-mode: false

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v3
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          ANSIBLE_HOST: ${{secrets.ANSIBLE_HOST}}
          ANSIBLE_USER: ${{secrets.ANSIBLE_USER}}
          ENV_FILE: "${{ secrets.TRAEFIK_POSTGRES_ENV_FILE }}"
        with:
          # Required, playbook filepath
          playbook: infra/Ansible/playbooks/deploy-lb+db.yml
          # Optional, SSH private key
          key: ${{secrets.SSH_PRIVATE_KEY}}
          # Optional, SSH known hosts file content
          known_hosts: ${{secrets.SSH_KNOWN_HOSTS}}
          options: |
            --inventory infra/Ansible/inventory/inventory.yml
            --verbose
